name: 'Setup Opus Make'
description: 'Setup Opus Make'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: btb/opusmake
        ref: v6.12
        path: OPUS
    - run: |
        echo "$GITHUB_WORKSPACE/OPUS/NT" >> "$GITHUB_PATH"
      shell: bash
